USE expense_db;

INSERT INTO categories(name, createdAt, updatedAt)
VALUES('Rent/Mortgage', CURRENT_TIME(), CURRENT_TIME()),
VALUES('Utilities', CURRENT_TIME(), CURRENT_TIME()),
VALUES('Subscriptions', CURRENT_TIME(), CURRENT_TIME()),
VALUES('Mobile', CURRENT_TIME(), CURRENT_TIME()),
VALUES('Gas', CURRENT_TIME(), CURRENT_TIME()),
VALUES('Groceries', CURRENT_TIME(), CURRENT_TIME()),
VALUES('Misc Food', CURRENT_TIME(), CURRENT_TIME()),
VALUES('Entertainment', CURRENT_TIME(), CURRENT_TIME()),
VALUES('Clothing', CURRENT_TIME(), CURRENT_TIME()),
VALUES('Charity', CURRENT_TIME(), CURRENT_TIME()),
VALUES('Leisure', CURRENT_TIME(), CURRENT_TIME()),
VALUES('Health', CURRENT_TIME(), CURRENT_TIME()),
VALUES('Credit card/Loans', CURRENT_TIME(), CURRENT_TIME()),
VALUES('Leisure', CURRENT_TIME(), CURRENT_TIME()),

SELECT * FROM categories;